<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CleanFirmeza.Application\CleanFirmeza.Application.csproj" />
      <ProjectReference Include="..\CleanFirmeza.Domain\CleanFirmeza.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
      <PackageReference Include="coverlet.collector" Version="6.0.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjectionFixed" Version="5.1.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.22" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Cloud\" />
      <Folder Include="Configuration\" />
    </ItemGroup>

</Project>
