<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\CleanFirmeza.Application\CleanFirmeza.Application.csproj" />
      <ProjectReference Include="..\..\CleanFirmeza.Infrastructure\CleanFirmeza.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.22" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.22" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Products\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Products\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Products\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Products\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Products\Index.cshtml" />
    </ItemGroup>

</Project>
